name: Deploy React Site to GitHub Pages

on:
  push:
    branches: ["main"]  # Rodar quando houver push na branch principal (geralmente 'main')
  workflow_dispatch:  # Permite rodar manualmente a partir da aba Actions

permissions:
  contents: read  # Permissão para ler o conteúdo do repositório
  pages: write    # Permissão para escrever na branch do GitHub Pages
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false  # Não cancela deploys em andamento

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Fazer o checkout do código
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Configurar o Node.js (defina a versão de acordo com seu projeto)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Ajuste a versão conforme necessário

      # 3. Instalar as dependências do projeto React
      - name: Install dependencies
        run: |
          npm install  # Ou 'yarn install', se estiver usando Yarn

      # 4. Construir o projeto React (vai gerar a pasta 'build' ou 'build_dir' para produção)
      - name: Build React app
        run: |
          npm run build  # Ou 'yarn build', se estiver usando Yarn

      # 5. Upload do artefato gerado para GitHub Pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build  # Caminho da pasta de build gerada

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # 6. Deploy para GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          branch: gh-pages  # Pode ser 'gh-pages' ou a branch onde você quer hospedar o site
          folder: ./build   # A pasta gerada pelo build do React
